### ISSUE TITLE
By default, `dbi.scm` goes into the wrong directory. 

### ISSUE THREAD

**Issue by ghost** [opencog/guile-dbi#6]
See this script:

https://gitlab.com/Lockywolf/lwfslackbuilds/-/blob/master/61_artanis_deps/guile-dbi/guile-dbi.SlackBuild

Configuring like this:
```
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --disable-static 

make
make install DESTDIR=$PKG
mkdir -p "$PKG"/usr/share/guile/3.0/
mv "$PKG"/dbi "$PKG"/usr/share/guile/3.0/
```

I still have to move `/dbi`/ to `/usr/share/guile/3.0/` because autotools installs them in the wrong place.

**Comment by linas** [comment]
Let's look at this more carefully:
```
make install DESTDIR=$PKG
mkdir -p "$PKG"/usr/share/guile/3.0/
mv "$PKG"/dbi "$PKG"/usr/share/guile/3.0/
```
Lets look at the last line  first. You were complaining that `/dbi/dbi.scm` was being installed as root. That implies that `$PKG` is the empty string. That implies that the first line is forcing the install to go into root.  Try just plain `make install`, does that fix it?

**Comment by ghost** [comment]
It does not, imply that "$PKG" is an empty string, Linas. It implies that `dbi` is installed under the root of `$DESTDIR`, which is _not_ where guile keeps its files.

 >Try just plain make install, does that fix it?

Try it yourself.

**Comment by linas** [comment]
OK, here's the deal. I can reproduce this problem if I put `guile.m4` in a place where `aclocal` can't find it. It normally looks in location `aclocal --print-ac-dir`.  To solve this problem, I then do
```
ACLOCAL_PATH=/path/to/wherever/share/aclocal/ ./autogen.sh --no-configure
```
and then the rest of the build steps, and then the problem goes away.  I assume this explains your bug, and so I'm closing this now.  If not, re-open or open a new issue.
